language: node_js
branches:
  only:
  - master
node_js:
- '12'
before_install:
- openssl aes-256-cbc -K $encrypted_2c4c9a008ff2_key -iv $encrypted_2c4c9a008ff2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
addons:
  ssh_known_hosts: 192.241.157.86
before_deploy:
- npm install -g pm2
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy && pm2 kill
  on:
    branch: master
